# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_fibheap')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_fibheap')
    _fibheap = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fibheap', [dirname(__file__)])
        except ImportError:
            import _fibheap
            return _fibheap
        try:
            _mod = imp.load_module('_fibheap', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _fibheap = swig_import_helper()
    del swig_import_helper
else:
    import _fibheap
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class FibHeapNode(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FibHeapNode, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FibHeapNode, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _fibheap.new_FibHeapNode()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibheap.delete_FibHeapNode
    __del__ = lambda self: None

    def __eq__(self, RHS):
        return _fibheap.FibHeapNode___eq__(self, RHS)

    def __lt__(self, RHS):
        return _fibheap.FibHeapNode___lt__(self, RHS)

    def Print(self):
        return _fibheap.FibHeapNode_Print(self)
FibHeapNode_swigregister = _fibheap.FibHeapNode_swigregister
FibHeapNode_swigregister(FibHeapNode)

class FibHeap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FibHeap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FibHeap, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _fibheap.new_FibHeap()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _fibheap.delete_FibHeap
    __del__ = lambda self: None

    def Insert(self, NewNode):
        return _fibheap.FibHeap_Insert(self, NewNode)

    def Union(self, OtherHeap):
        return _fibheap.FibHeap_Union(self, OtherHeap)

    def Minimum(self):
        return _fibheap.FibHeap_Minimum(self)

    def ExtractMin(self):
        return _fibheap.FibHeap_ExtractMin(self)

    def DecreaseKey(self, theNode, NewKey):
        return _fibheap.FibHeap_DecreaseKey(self, theNode, NewKey)

    def Delete(self, theNode):
        return _fibheap.FibHeap_Delete(self, theNode)

    def GetHeapOwnership(self):
        return _fibheap.FibHeap_GetHeapOwnership(self)

    def SetHeapOwnership(self):
        return _fibheap.FibHeap_SetHeapOwnership(self)

    def ClearHeapOwnership(self):
        return _fibheap.FibHeap_ClearHeapOwnership(self)

    def GetNumNodes(self):
        return _fibheap.FibHeap_GetNumNodes(self)

    def GetNumTrees(self):
        return _fibheap.FibHeap_GetNumTrees(self)

    def GetNumMarkedNodes(self):
        return _fibheap.FibHeap_GetNumMarkedNodes(self)

    def Print(self, Tree=None, theParent=None):
        return _fibheap.FibHeap_Print(self, Tree, theParent)
FibHeap_swigregister = _fibheap.FibHeap_swigregister
FibHeap_swigregister(FibHeap)

# This file is compatible with both classic and new-style classes.


